### ISSUE TITLE
在项目中使用未能渲染出节点

### ISSUE THREAD

**Issue by Germxu** [ht-sauce/elui-china-area-dht#1]
![image](https://user-images.githubusercontent.com/20300863/145683650-7122e3e9-25a3-44e2-be59-deb97c7a9645.png)

单独建立项目可以使用, 没有查出问题

**Comment by Germxu** [comment]
依赖冲突导致的,  项目用了vue 3.0.0,  插件需要3.0.5, 问题真的很难排查出来

**Comment by ht-sauce** [comment]
vue版本建议升级为最新版本，vue3.0.0版本太老了。我用的那会vue出了不少bug。现在发了2.0版本，只是把核心库升级。但是代码一个都没改。如果不闲麻烦的话，可以把我的源码拿走，自己写一份。核心好简单
