### ISSUE TITLE
el-plus 2.3用不了

### ISSUE THREAD

**Issue by sparGuan** [ht-sauce/elui-china-area-dht#4]
el-plus 2.3用不了

**Comment by G-Z-Ming** [comment]
他这个插件依赖el-cascader，你需要全局注册
![aaaa123](https://user-images.githubusercontent.com/40484256/178885166-9d8cfdc5-baad-4469-a925-98ae3a80f333.png)

**Comment by ht-sauce** [comment]
> el-plus 2.3用不了

上面的哥们给出结果了。不过不用全局注册。只要能正常解析级联组件就好了
