### ISSUE TITLE
希望能添加一个属性开启和关闭港澳台选项

### ISSUE THREAD

**Issue by iilitlleboyii** [ht-sauce/elui-china-area-dht#5]
大佬，请问怎么关闭港澳台的选项？

**Comment by ht-sauce** [comment]
> 大佬，请问怎么关闭港澳台的选项？

请拷贝https://github.com/ht-sauce/elui-china-area-dht/blob/master/src/EluiChinaAreaDht/src/ChinaArea.ts，源码自行实现吧。核心还是对于第三方数据的省市区数据维护
